# -*- coding: utf-8 -*-
"""602257_atikhom_heart_disease

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jS5eXa_vY-QasWCCzIZlT-fgU_cUO4_l

## 1. Install & Import
"""

!pip install lightgbm xgboost imbalanced-learn -q

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import fbeta_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
import xgboost as xgb
from imblearn.over_sampling import SMOTE

pd.set_option('display.max_columns', None)
print('✅ Done')

"""## 2. Load Data"""

# 1. เชื่อมต่อ Google Drive เพื่อดึงข้อมูลมาใช้
from google.colab import drive
drive.mount('/content/drive')

# 2. กำหนดที่อยู่ไฟล์ (Path) ของข้อมูล Train, Test และไฟล์ตัวอย่างการส่งคำตอบ
TRAIN_PATH = '/content/drive/MyDrive/super-ai-engineer-season-6-heart-disease-2569/train.csv'
TEST_PATH  = '/content/drive/MyDrive/super-ai-engineer-season-6-heart-disease-2569/test.csv'
SUB_PATH   = '/content/drive/MyDrive/super-ai-engineer-season-6-heart-disease-2569/sample_submission.csv'

# 3. อ่านไฟล์ CSV เข้ามาเป็นตาราง (DataFrame)
train = pd.read_csv(TRAIN_PATH)
test  = pd.read_csv(TEST_PATH)
sample_sub = pd.read_csv(SUB_PATH)

# แสดงขนาดของข้อมูลและตัวอย่าง 3 แถวแรก
print(f'Train shape : {train.shape}')
print(f'Test  shape : {test.shape}')
print(f'Sample sub  : {sample_sub.shape}')
display(train.head(3))

"""## 3. Diagnose: ตรวจสอบ Target Column ก่อนเสมอ"""

TARGET = 'History of HeartDisease or Attack'

# ── ดู unique values ของ target จริงๆ ────────────────────────────────────────
print('=== Target unique values ===')
print(train[TARGET].value_counts())
print('\nDtype:', train[TARGET].dtype)
print('\nSample values:', train[TARGET].unique()[:10])

# ── Class imbalance ratio ─────────────────────────────────────────────────────
vc = train[TARGET].value_counts()
print(f'\n⚠️  Imbalance ratio: {vc.max() / vc.min():.1f}x')
print('→ ยิ่ง ratio สูง ยิ่งต้องการ threshold ต่ำ และ class_weight สูง')

# ── Drop rows where target is NaN ──────────────────────────────────────────
TARGET = 'History of HeartDisease or Attack'

n_before  = len(train)
train      = train.dropna(subset=[TARGET]).copy()
n_after   = len(train)

print(f'Dropped : {n_before - n_after:,} rows')
print(f'Remaining: {n_after:,} rows')
print(train[TARGET].value_counts())

# ── Recompute scale_pos_weight ─────────────────────────────────────────────
n_no  = (train[TARGET] == 'No').sum()
n_yes = (train[TARGET] == 'Yes').sum()
scale_pos_weight = n_no / n_yes

print(f'\nscale_pos_weight = {scale_pos_weight:.2f}')

# ── ดู test ID format ─────────────────────────────────────────────────────────
print('Test ID sample:')
print(test.iloc[:3, :2])   # ID + first feature
print('\nSample submission:')
print(sample_sub.head(3))

"""## 4. Preprocessing"""

def preprocess(train_df, test_df, target_col):
    """ ฟังก์ชันสำหรับเตรียมข้อมูลให้พร้อมก่อนส่งให้ AI เรียนรู้ """
    train_proc = train_df.copy()
    test_proc  = test_df.copy()

    # แยก ID ไว้สำหรับใช้ตอนส่งคำตอบ
    id_col   = 'ID'
    test_ids = test_proc[id_col].values

    # เปลี่ยนคำตอบ (Target) จาก 'Yes'/'No' ให้เป็นตัวเลข 1 กับ 0
    y_raw = train_proc[target_col]
    if y_raw.dtype == object:
        y = y_raw.map({'Yes': 1, 'No': 0, 'YES': 1, 'NO': 0, 'yes': 1, 'no': 0})
    else:
        y = y_raw.astype(int)

    # ลบคอลัมน์ที่ไม่ใช่ฟีเจอร์ในการทำนายออก (เช่น ID และตัวคำตอบเอง)
    train_proc = train_proc.drop(columns=[id_col, target_col], errors='ignore')
    test_proc  = test_proc.drop(columns=[id_col], errors='ignore')

    n_train  = len(train_proc)
    combined = pd.concat([train_proc, test_proc], axis=0, ignore_index=True)

    # เปลี่ยนข้อมูลที่เป็นตัวหนังสือ (เช่น เพศ, ประวัติการสูบบุหรี่) ให้เป็นตัวเลข
    binary_map = {'Yes': 1, 'No': 0}
    for col in combined.select_dtypes(include='object').columns:
        uniq = set(combined[col].dropna().unique())
        if uniq.issubset(set(binary_map.keys())):
            combined[col] = combined[col].map(binary_map)
        else:
            le = LabelEncoder()
            combined[col] = le.fit_transform(combined[col].astype(str))

    # เติมค่าว่างด้วยค่ากลาง (Median) เพื่อไม่ให้โมเดล Error
    for col in combined.columns:
        if combined[col].isnull().any():
            combined[col].fillna(combined[col].median(), inplace=True)

    # แยกข้อมูลกลับเป็นชุด Train (ไว้ฝึก) และ Test (ไว้ส่งคำตอบ)
    X_train = combined.iloc[:n_train].reset_index(drop=True).astype(float)
    X_test  = combined.iloc[n_train:].reset_index(drop=True).astype(float)

    return X_train, y.reset_index(drop=True), X_test, test_ids

X_train, y_train, X_test, test_ids = preprocess(train, test, TARGET)

"""## 5. Compute Class Weights"""

n_neg = (y_train == 0).sum()
n_pos = (y_train == 1).sum()
scale_pos_weight = n_neg / n_pos

print(f'n_neg (No) : {n_neg}')
print(f'n_pos (Yes): {n_pos}')
print(f'scale_pos_weight: {scale_pos_weight:.2f}')
print(f'\n→ โมเดลจะให้น้ำหนัก class Yes สูงกว่า {scale_pos_weight:.1f}x')

"""## 6. F2 Utility Functions"""

def f2_weighted(y_true, y_pred):
    return fbeta_score(y_true, y_pred, beta=2, average='weighted')

def find_best_threshold(y_true, y_proba, beta=2, steps=200):
    """Grid search threshold 0.05–0.95 → maximise F2 weighted."""
    thresholds = np.linspace(0.05, 0.95, steps)
    scores = [f2_weighted(y_true, (y_proba >= t).astype(int)) for t in thresholds]
    best_idx = int(np.argmax(scores))
    best_t   = thresholds[best_idx]
    best_s   = scores[best_idx]

    # Plot
    plt.figure(figsize=(9, 3))
    plt.plot(thresholds, scores, color='royalblue')
    plt.axvline(best_t, color='red', linestyle='--', label=f'Best={best_t:.3f} (F2={best_s:.5f})')
    plt.xlabel('Threshold')
    plt.ylabel('F2 Score (weighted)')
    plt.title('F2 Score vs Classification Threshold')
    plt.legend()
    plt.tight_layout()
    plt.show()

    print(f'✅ Best threshold: {best_t:.4f}  →  F2 = {best_s:.5f}')
    return best_t, best_s

print('✅ F2 utils ready')

"""## 7. Train Models (5-Fold CV + OOF)"""

# ── Model Definitions ─────────────────────────────────────────────────────────
lgbm_params = dict(
    n_estimators      = 1000,
    learning_rate     = 0.03,
    num_leaves        = 63,
    max_depth         = -1,
    min_child_samples = 10,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.05,
    reg_lambda        = 0.05,
    scale_pos_weight  = scale_pos_weight,  # KEY: ให้น้ำหนัก Yes
    class_weight      = 'balanced',
    random_state      = 42,
    verbosity         = -1,
    n_jobs            = -1,
)

xgb_params = dict(
    n_estimators      = 1000,
    learning_rate     = 0.03,
    max_depth         = 6,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.05,
    reg_lambda        = 0.5,
    scale_pos_weight  = scale_pos_weight,  # KEY
    eval_metric       = 'logloss',
    use_label_encoder = False,
    random_state      = 42,
    n_jobs            = -1,
)

rf_params = dict(
    n_estimators     = 500,
    max_depth        = 12,
    min_samples_leaf = 5,
    class_weight     = {0: 1, 1: scale_pos_weight},  # KEY
    random_state     = 42,
    n_jobs           = -1,
)

models = {
    'LightGBM'    : lgb.LGBMClassifier(**lgbm_params),
    'XGBoost'     : xgb.XGBClassifier(**xgb_params),
    'RandomForest': RandomForestClassifier(**rf_params),
}

print('✅ Models defined')

N_FOLDS = 5
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)
smote = SMOTE(random_state=42)

oof_preds  = {name: np.zeros(len(X_train)) for name in models}
test_preds = {name: np.zeros(len(X_test))  for name in models}
cv_f2      = {name: [] for name in models}

for model_name, model in models.items():
    print(f'\n{'─'*50}')
    print(f'  {model_name}')
    print('─'*50)

    for fold, (trn_idx, val_idx) in enumerate(skf.split(X_train, y_train), 1):
        X_tr  = X_train.iloc[trn_idx]
        y_tr  = y_train.iloc[trn_idx]
        X_val = X_train.iloc[val_idx]
        y_val = y_train.iloc[val_idx]

        # SMOTE เฉพาะ training split
        X_tr_sm, y_tr_sm = smote.fit_resample(X_tr, y_tr)

        model.fit(X_tr_sm, y_tr_sm)

        val_proba = model.predict_proba(X_val)[:, 1]
        oof_preds[model_name][val_idx] = val_proba
        test_preds[model_name] += model.predict_proba(X_test)[:, 1] / N_FOLDS

        # F2 at threshold=0.3 (lower than 0.5 because F2 prefers Recall)
        val_pred = (val_proba >= 0.3).astype(int)
        f2 = f2_weighted(y_val, val_pred)
        cv_f2[model_name].append(f2)
        print(f'  Fold {fold}: F2@0.3 = {f2:.5f}')

    m = np.mean(cv_f2[model_name])
    s = np.std(cv_f2[model_name])
    print(f'  ➜ Mean F2: {m:.5f} ± {s:.5f}')

"""## 8. 🔧 Find Best Threshold per Model"""

best_t_per_model = {}

for model_name in models:
    print(f'\n[{model_name}]')
    t, s = find_best_threshold(y_train, oof_preds[model_name])
    best_t_per_model[model_name] = t
    y_p = (oof_preds[model_name] >= t).astype(int)
    print(classification_report(y_train, y_p, target_names=['No','Yes']))

"""## 9. Ensemble"""

# Weighted average (weight = mean CV F2)
raw_weights = {k: np.mean(v) for k, v in cv_f2.items()}
total_w     = sum(raw_weights.values())
weights     = {k: v / total_w for k, v in raw_weights.items()}
print('Ensemble weights:', {k: f'{v:.3f}' for k, v in weights.items()})

oof_ens  = sum(oof_preds[n]  * w for n, w in weights.items())
test_ens = sum(test_preds[n] * w for n, w in weights.items())

print('\n[Ensemble OOF]')
best_t_ens, best_f2_ens = find_best_threshold(y_train, oof_ens)

y_ens_pred = (oof_ens >= best_t_ens).astype(int)
print(classification_report(y_train, y_ens_pred, target_names=['No','Yes']))

# Confusion matrix
cm = confusion_matrix(y_train, y_ens_pred)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No','Yes'], yticklabels=['No','Yes'])
plt.title(f'Ensemble OOF  |  Threshold={best_t_ens:.3f}  |  F2={best_f2_ens:.5f}')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.tight_layout(); plt.show()

"""## 10. Probability Distribution Check
> ถ้าโมเดลดี: กราฟ Yes และ No ควรแยกจากกัน
"""

plt.figure(figsize=(9, 4))
plt.hist(oof_ens[y_train == 0], bins=60, alpha=0.6, label='No (0)',  color='steelblue')
plt.hist(oof_ens[y_train == 1], bins=60, alpha=0.6, label='Yes (1)', color='tomato')
plt.axvline(best_t_ens, color='black', linestyle='--', label=f'Threshold={best_t_ens:.3f}')
plt.xlabel('Predicted Probability (Yes)')
plt.ylabel('Count')
plt.title('OOF Probability Distribution by True Label')
plt.legend()
plt.tight_layout()
plt.show()

print('OOF Proba stats for Yes class:')
print(pd.Series(oof_ens[y_train == 1]).describe())
print('\nOOF Proba stats for No class:')
print(pd.Series(oof_ens[y_train == 0]).describe())

"""## 11. Generate Submissions
> สร้าง 3 versions: best threshold, aggressive (lower), conservative
"""

def make_submission(test_proba, threshold, filename, test_ids):
    y_pred  = (test_proba >= threshold).astype(int)
    labels  = pd.Series(y_pred).map({1: 'Yes', 0: 'No'}).values
    sub = pd.DataFrame({
        'ID': test_ids,
        'History of HeartDisease or Attack': labels
    })
    sub.to_csv(filename, index=False)
    n_yes = (sub['History of HeartDisease or Attack'] == 'Yes').sum()
    n_no  = (sub['History of HeartDisease or Attack'] == 'No').sum()
    print(f'[{filename}] Yes={n_yes} | No={n_no} | Yes%={n_yes/len(sub)*100:.1f}%')
    return sub

print('=== Submission Files ===')

# Version 1: Best threshold (from grid search)
sub1 = make_submission(test_ens, best_t_ens,
                        'submission_v1_best.csv', test_ids)

# Version 2: Aggressive threshold (lower → more Yes → higher Recall)
agg_t = max(best_t_ens - 0.10, 0.10)
sub2  = make_submission(test_ens, agg_t,
                        'submission_v2_aggressive.csv', test_ids)

# Version 3: Very aggressive (เพิ่ม Yes มากสุด)
sub3 = make_submission(test_ens, 0.20,
                        'submission_v3_very_aggressive.csv', test_ids)

print(f'\n✅ OOF F2 at best threshold: {best_f2_ens:.5f}')
print('→ ลอง submit ทีละ version แล้วดูว่า Kaggle ให้ F2 เท่าไหร่')

"""## 12. Diagnose: Why was F2 low?"""

print('='*55)
print('  DIAGNOSIS: OOF predictions at different thresholds')
print('='*55)

header = f'{"Threshold":>10} | {"F2":>8} | {"Recall(Yes)":>12} | {"Prec(Yes)":>10} | {"#Yes pred":>10}'
print(header)
print('-'*60)

for t in np.arange(0.10, 0.70, 0.05):
    y_p    = (oof_ens >= t).astype(int)
    f2     = f2_weighted(y_train, y_p)
    recall = (y_p[y_train == 1] == 1).mean() if (y_train == 1).sum() > 0 else 0
    prec   = (y_train[y_p == 1] == 1).mean() if y_p.sum() > 0 else 0
    n_yes  = y_p.sum()
    marker = ' ← best' if abs(t - best_t_ens) < 0.03 else ''
    print(f'{t:>10.2f} | {f2:>8.5f} | {recall:>12.3f} | {prec:>10.3f} | {n_yes:>10}{marker}')

# ── ดาวน์โหลดใน Colab ────────────────────────────────────────────────────────
try:
    from google.colab import files
    for f in ['submission_v1_best.csv',
              'submission_v2_aggressive.csv',
              'submission_v3_very_aggressive.csv']:
        files.download(f)
    print('✅ Downloaded all submissions!')
except:
    print('Not in Colab — files are in working directory.')

# ── Cell A: ดูว่าตอนนี้โมเดลทำนาย Yes กี่ % ──────────────────────────────
print('=== OOF Probability Stats ===')
print(f'Mean P(Yes) — true Yes : {oof_ens[y_train==1].mean():.4f}')
print(f'Mean P(Yes) — true No  : {oof_ens[y_train==0].mean():.4f}')

print('\n=== Threshold Sweep ===')
print(f'{"Threshold":>10} | {"F2":>8} | {"Recall(Yes)":>12} | {"#Yes pred":>10} | {"Yes%":>6}')
print('-' * 58)
for t in np.arange(0.05, 0.55, 0.05):
    y_p     = (oof_ens >= t).astype(int)
    f2      = fbeta_score(y_train, y_p, beta=2, average='weighted')
    recall  = (y_p[y_train==1] == 1).mean()
    n_yes   = y_p.sum()
    pct     = n_yes / len(y_p) * 100
    print(f'{t:>10.2f} | {f2:>8.5f} | {recall:>12.3f} | {n_yes:>10,} | {pct:>5.1f}%')

# ── Cell B: Submit ด้วย threshold ที่ดีที่สุดจากตารางด้านบน ───────────────
# *** เปลี่ยน BEST_T ให้ตรงกับแถวที่ F2 สูงสุดในตาราง ***
BEST_T = 0.15   # <── แก้ตรงนี้

y_test_pred = (test_ens >= BEST_T).astype(int)
print(f'Yes: {y_test_pred.sum():,}  |  No: {(y_test_pred==0).sum():,}  |  Yes%: {y_test_pred.mean()*100:.1f}%')

submission = pd.DataFrame({
    'ID': test_ids,
    'History of HeartDisease or Attack': pd.Series(y_test_pred).map({1:'Yes', 0:'No'})
})
submission.to_csv('submission_final.csv', index=False)
print(submission.head())

# Colab download
try:
    from google.colab import files
    files.download('submission_final.csv')
except:
    pass

# หา best threshold และแสดงผลชัดๆ
print(f'{"Threshold":>10} | {"F2":>8} | {"Recall(Yes)":>12} | {"Yes%":>6}')
print('-' * 46)

best_f2, best_t = 0, 0
for t in np.arange(0.05, 0.90, 0.05):
    y_p    = (oof_ens >= t).astype(int)
    f2     = fbeta_score(y_train, y_p, beta=2, average='weighted')
    recall = (y_p[y_train==1] == 1).mean()
    pct    = y_p.mean() * 100
    marker = ' ◄ BEST' if f2 > best_f2 else ''
    if f2 > best_f2:
        best_f2, best_t = f2, t
    print(f'{t:>10.2f} | {f2:>8.5f} | {recall:>12.3f} | {pct:>5.1f}%{marker}')

print(f'\n→ Best T = {best_t:.2f}  |  Best F2 = {best_f2:.5f}')

# ส่วนนี้คือการหา Threshold (จุดตัด) ที่ดีที่สุด
# ปกติ AI จะทำนายเป็นค่าความน่าจะเป็น 0.0 - 1.0
# เราต้องเลือกจุดตัดว่าเท่าไหร่ถึงจะเรียกว่า 'Yes' เพื่อให้ได้คะแนน F2 สูงที่สุด

print(f'{"Threshold":>10} | {"F2_macro":>10} | {"F2_binary":>10} | {"Recall_Yes":>11} | {"Yes%":>6}')
print('-' * 60)

best_macro, best_binary = 0, 0
best_t_macro, best_t_binary = 0, 0

# วนลูปทดสอบจุดตัดตั้งแต่ 0.05 ถึง 0.90
for t in np.arange(0.05, 0.90, 0.05):
    y_p = (oof_ens >= t).astype(int)

    # คำนวณคะแนนแบบต่างๆ (F2 คือการเน้นจับกลุ่มคนที่เป็นโรคให้ได้มากที่สุด)
    f2_macro  = fbeta_score(y_train, y_p, beta=2, average='macro')
    f2_binary = fbeta_score(y_train, y_p, beta=2, average='binary', pos_label=1)
    recall    = (y_p[y_train==1] == 1).mean()
    pct       = y_p.mean() * 100

    if f2_macro  > best_macro:  best_macro,  best_t_macro  = f2_macro,  t
    if f2_binary > best_binary: best_binary, best_t_binary = f2_binary, t

    print(f'{t:>10.2f} | {f2_macro:>10.5f} | {f2_binary:>10.5f} | {recall:>11.3f} | {pct:>5.1f}%')

print(f'\nสรุป: จุดตัดที่ดีที่สุดสำหรับ Macro F2 คือ {best_t_macro} (คะแนน {best_macro:.5f})')

submissions = {
    'submission_BINARY_t0.60.csv' : 0.60,
    'submission_MACRO_t0.75.csv'  : 0.75,
    'submission_MACRO_t0.70.csv'  : 0.70,
}

for fname, t in submissions.items():
    y_p    = (test_ens >= t).astype(int)   # ← ใช้ test_ens ไม่ใช่ oof_ens
    labels = pd.Series(y_p).reset_index(drop=True).map({1: 'Yes', 0: 'No'})
    sub = pd.DataFrame({
        'ID'                                : pd.Series(test_ids).reset_index(drop=True),
        'History of HeartDisease or Attack' : labels
    })
    sub.to_csv(fname, index=False)
    print(f'[{fname}]  Yes={y_p.sum():,} ({y_p.mean()*100:.1f}%)')

try:
    from google.colab import files
    for fname in submissions:
        files.download(fname)
except: pass